# Generated by Django 2.0 on 2019-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('starsgazers', models.IntegerField(max_length=40)),
                ('commits_this_week', models.IntegerField(max_length=40)),
                ('commits_last_week', models.IntegerField(max_length=40)),
            ],
            options={
                'verbose_name': 'repo',
                'ordering': ['starsgazers'],
            },
        ),
    ]
