# Generated by Django 2.0 on 2019-04-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitInsights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='commits_last_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='commits_this_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='repository',
            name='starsgazers',
            field=models.IntegerField(),
        ),
    ]
