# Generated by Django 2.0 on 2019-05-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gitInsights', '0003_repository_top_langage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='top_langage',
            new_name='top_language',
        ),
    ]
